### ISSUE TITLE
error

### ISSUE THREAD

**Issue by viraj310** [xaneem/flipbot#1]
![image](https://cloud.githubusercontent.com/assets/15348278/11600314/d1a87376-9af1-11e5-8587-a1dc5e912974.png)
 it shows following error

**Comment by xaneem** [comment]
I've tested it - it works. You have to type something in the keyword - eg: "keyboard".

**Comment by viraj310** [comment]
![image](https://cloud.githubusercontent.com/assets/15348278/11612737/f3514de6-9c2b-11e5-95ce-9ab32b4a4853.png)

**Comment by viraj310** [comment]
plzz u will tell me steps to run it... m using xampp...

**Comment by xaneem** [comment]
You can't run it using XAMPP. It uses [node.js](https://nodejs.org/) and [CasperJS](http://casperjs.org/). After installing both, open the `server` folder and run `npm install` from the command line.
